// 預設範例情境（供升等比較頁使用）
import type { SalaryScenario } from "./types";

export const DEFAULT_SALARY_SCENARIO: SalaryScenario = {
  rank: 6,
  point: 345,
  professionalAllowanceTable: "professional_allowance_table_7",
  engineeringExtra: true,
  pensionSystem: "personal_account",
  healthInsuranceDependents: 0,
  supervisoryAllowance: 0,
};

export const SCENARIOS: Array<{ label: string; before: SalaryScenario; after: SalaryScenario }> = [
  {
    label: "工程人員升等（薦任七→八）",
    before: {
      rank: 7,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_7",
      engineeringExtra: true,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
    after: {
      rank: 8,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_7",
      engineeringExtra: true,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
  },
  {
    label: "行政人員升等（薦任七→八）",
    before: {
      rank: 7,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_4",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
    after: {
      rank: 8,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_4",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
  },
  {
    label: "主計人員升等（薦任七→八）",
    before: {
      rank: 7,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_1",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 1,
      supervisoryAllowance: 0,
    },
    after: {
      rank: 8,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_1",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 1,
      supervisoryAllowance: 0,
    },
  },
  {
    label: "人事人員升等（薦任七→八）",
    before: {
      rank: 7,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_2",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
    after: {
      rank: 8,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_2",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
  },
  {
    label: "薦任科長就任主管（附主管加給）",
    before: {
      rank: 8,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_4",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
    after: {
      rank: 8,
      point: 475,
      professionalAllowanceTable: "professional_allowance_table_4",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 3600,
    },
  },
  {
    label: "委任升薦任（委五→薦六）",
    before: {
      rank: 5,
      point: 360,
      professionalAllowanceTable: "professional_allowance_table_4",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
    after: {
      rank: 6,
      point: 360,
      professionalAllowanceTable: "professional_allowance_table_4",
      engineeringExtra: false,
      pensionSystem: "old",
      healthInsuranceDependents: 0,
      supervisoryAllowance: 0,
    },
  },
];
